<div class="btn-breadcrumb">
    <a href="#/" ><i class="fa-home"></i><span class="sr-only">{{t 'home'}}</span></a>
    <a href="#/tools">{{t 'tools'}}</a>
    <a href="#/tools/ca">{{t 'tools_download_ca'}}</a>
</div>

<div class="separator"></div>

<div class="panel panel-default">
    <div class="panel-body">
    	<p>{{t 'tools_download_ca_desc'}}</p>
    	<a href="ca.crt" class="btn btn-success">CA.crt</a>
    </div>
</div>
