<div class="pull-left">
    <a href="#/tools" class="btn btn-default slide back">
    	<span class="fa-chevron-left"></span> {{t 'tools'}}
    </a>
</div>
<div class="clearfix"></div>
<h1 class="view-title">{{t 'tools_download_ca'}}</h1>
<div class="br"></div>

<div class="panel panel-default">
    <div class="panel-body">
    	<p>{{t 'tools_download_ca_desc'}}</p>
    	<a href="ca.crt" class="btn btn-success">CA.crt</a>
    </div>
</div>
