<div class="pull-left">
    <a href="#/" class="btn btn-default slide back">
    	<span class="fa-chevron-left"></span> Menu
    </a>
</div>
<div class="clearfix"></div>
<div class="view-title">Tools</div>
<div class="br"></div>


<div class="list-group">
{{#links}}
    <a href="{{path}}" class="list-group-item slide">
        <span class="fa-chevron-right pull-right"></span>
        <h4 class="list-group-item-heading">{{name}}</h4>
    </a>
{{/links}}
</div>

