<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">{{Username}}</h3>
    </div>
    <!--<div class="panel-body"></div>-->
    <ul class="list-group">
        <li class="list-group-item"><strong>Fullname</strong>&nbsp;&nbsp; {{Fullname}}</li>
        <li class="list-group-item"><strong>Username</strong>&nbsp;&nbsp; {{Username}}</li>
        <li class="list-group-item"><strong>Mail</strong>&nbsp;&nbsp; {{Mail}}</li>
    </ul>
</div>
