<div class="pull-left">
    <a href="#/" class="btn btn-default slide back">
        <span class="fa-chevron-left"></span> {{t 'menu'}}
    </a>
</div>
<div class="clearfix"></div>
<h1 class="view-title">{{t 'backup'}}</h1>
<div class="br"></div>

<div class="alert alert-warning">
    <span class="fa-exclamation-triangle"></span>
    <strong>{{t 'backup_warning_title'}}</strong>
    <br>{{t 'backup_warning_desc'}}
</div>