<div class="pull-left">
    <a href="#/" class="btn btn-default slide back">
        <span class="fa-chevron-left"></span> Menu
    </a>
</div>
<div class="clearfix"></div>
<h1 class="view-title">Backup</h1>
<div class="br"></div>

<div class="alert alert-warning">
    <span class="fa-exclamation-triangle"></span>
    <strong>The backup system is not implemented yet.</strong>
    <br>
    You should take care of backing up your data yourself for now.
</div>