name: Auto apply Prettier

on:
  push:
      branches:
          - dev
  pull_request:

jobs:
  autolintfix:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install yarn dependencies
      run: yarn install --frozen-lockfile
    - name: Apply prettier and eslint fix
      run: yarn lintfix
    - name: Run type checking
      run: yarn type-check
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ":art: Format code with Prettier and ESLint"
